[tool.poetry]
name = "veckeysearch"
version = "1.0.0"
description = "vector search package"
authors = ["Jungeun17 <kkhj826@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain-community = "^0.3.24"
langchain-text-splitters = "^0.3.8"
opensearch-py = "^2.8.0"
langchain-openai = "^0.3.19"
langgraph = "^0.4.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
